export const demoData = {
  metadata: {
    dataVersion: '2',
    matchId: 'EUW1_6251250036',
    participants: [
      'rqlu2uq9w3fhB3rXQPO2GESfV85HObXBU2sejyX9WH6Mr4FgOIyPvJHnM2SpUR_nD4Ew83FqRzWnBw',
      '0pkNAVmAHAxdqgODFsrByh_Mgmk4VHVSFP9t8xN4M04gS1BsyZjaCEFyQ93dNSHkuch0z0bIf-9NtQ',
      '9FjB6i7tI4u23tLjO7Rn_VJ2P23M1FGP4bzndCLpQwYyQHBJ9LpQ2EbZn4zCdRzmmZqpbgsCKf0aNQ',
      'xzKMuv1c0l-rert5giH4MzCuShb6Uk6k0nB0Gp8xRZE2LAsYfEXmNd8tKXX4dVE2QofDFCNfckSgNw',
      '2DUofDHHiwu-YTN3yW3tOrDDcxXPULW4mN70Qf2j0KyRKtN6ptlr7wxeqQhiewh4OcCMuE3AYYMdMg',
      'pTEkf0XXZU6rojXpyBJDcRGLmCm4C3qb715oV7PssrtnWLjIWk3MQvhzTVjgdrrIX5-_4Vv-YlQTSQ',
      '-jDFFhYg-D2loE_gqKVrS3gfPW9ciz-u7SeWLVxkjFd_3JjeZP86olVEYjxDR6HhifsbbYirjjZu6w',
      'aJpxtgajzgXG60HOETZVEdeGG75snVb5DtylxYi7R3Yj1uMFnQxYfgxJlyF6mTmnVR9bj1RWunHWJg',
      'rNInN8kgRJfPY5U0yFsvlAdnL1TbYH0F_dJgyhyFkJ9AEv6xojuyjTCFHG8VO79K7qW2nqHaYYSfXg',
      'QpxUlNthyJOgM2m0EjBq3rP4qDRLS7YPGcvD6BMryKkPpu-PBxLWoGxH5LPhE-3XxyPnNFQVGjXi8g'
    ]
  },
  info: {
    gameCreation: 1674767418803,
    gameDuration: 2436,
    gameEndTimestamp: 1674769884904,
    gameId: 6251250036,
    gameMode: 'CLASSIC',
    gameName: 'teambuilder-match-6251250036',
    gameStartTimestamp: 1674767448619,
    gameType: 'MATCHED_GAME',
    gameVersion: '13.1.489.3737',
    mapId: 11,
    participants: [
      {
        allInPings: 0,
        assistMePings: 1,
        assists: 7,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 755,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 22.500000059604645,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 600,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.2772632911496861,
          controlWardsPlaced: 1,
          damagePerMinute: 828.4382682882257,
          damageTakenOnTeamPercentage: 0.26187130060800484,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 10,
          dodgeSkillShotsSmallWindow: 10,
          doubleAces: 0,
          dragonTakedowns: 0,
          earliestBaron: 2083.768886412002,
          earliestElderDragon: 2375.8981544487788,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 1,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 51,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 0,
          fullTeamTakedown: 2,
          gameLength: 2436.3211091098337,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 406.4492223992212,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 14,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 1.7,
          killAfterHiddenWithAlly: 3,
          killParticipation: 0.4473684210526316,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 3,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 1,
          killsWithHelpFromEpicMonster: 1,
          knockEnemyIntoTeamAndKill: 11,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 73,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 13,
          maxKillDeficit: 10,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6630,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 1,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 14,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 1,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 57,
          skillshotsHit: 0,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          stealthWardsPlaced: 7,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 17,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 2,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.21043272338809405,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 4,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 1,
          turretPlatesTaken: 1,
          turretTakedowns: 4,
          turretsTakenWithRiftHerald: 10,
          twentyMinionsIn3SecondsCount: 9,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.5052258968353271,
          visionScorePerMinute: 0.4283579029138555,
          wardTakedowns: 2,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0
        },
        champExperience: 18538,
        champLevel: 18,
        championId: 92,
        championName: 'Riven',
        championTransform: 0,
        commandPings: 7,
        consumablesPurchased: 3,
        damageDealtToBuildings: 3975,
        damageDealtToObjectives: 9597,
        damageDealtToTurrets: 3975,
        damageSelfMitigated: 72118,
        dangerPings: 0,
        deaths: 10,
        detectorWardsPlaced: 1,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 4,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 16504,
        goldSpent: 15425,
        holdPings: 0,
        individualPosition: 'TOP',
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 0,
        item0: 6630,
        item1: 6333,
        item2: 3158,
        item3: 6694,
        item4: 3071,
        item5: 1031,
        item6: 3340,
        itemsPurchased: 24,
        killingSprees: 3,
        kills: 10,
        lane: 'TOP',
        largestCriticalStrike: 0,
        largestKillingSpree: 2,
        largestMultiKill: 1,
        longestTimeSpentLiving: 495,
        magicDamageDealt: 2355,
        magicDamageDealtToChampions: 1359,
        magicDamageTaken: 19765,
        needVisionPings: 0,
        neutralMinionsKilled: 23,
        nexusKills: 1,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 2,
        participantId: 1,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5007
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8010,
                  var1: 984,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 9111,
                  var1: 1367,
                  var2: 340,
                  var3: 0
                },
                {
                  perk: 9104,
                  var1: 18,
                  var2: 40,
                  var3: 0
                },
                {
                  perk: 8299,
                  var1: 1284,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8000
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8401,
                  var1: 553,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8444,
                  var1: 2253,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8400
            }
          ]
        },
        physicalDamageDealt: 192442,
        physicalDamageDealtToChampions: 29559,
        physicalDamageTaken: 28110,
        profileIcon: 539,
        pushPings: 1,
        puuid:
          'rqlu2uq9w3fhB3rXQPO2GESfV85HObXBU2sejyX9WH6Mr4FgOIyPvJHnM2SpUR_nD4Ew83FqRzWnBw',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'SOLO',
        sightWardsBoughtInGame: 0,
        spell1Casts: 442,
        spell2Casts: 92,
        spell3Casts: 187,
        spell4Casts: 34,
        summoner1Casts: 11,
        summoner1Id: 14,
        summoner2Casts: 6,
        summoner2Id: 4,
        summonerId: 'hlJtqeGNSgyd8z39h-_V7UhhozUrw4AB0q-2qmFpf2Xh5dg',
        summonerLevel: 100,
        summonerName: 'FreddwnZ',
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: 'TOP',
        timeCCingOthers: 34,
        timePlayed: 2436,
        totalDamageDealt: 200030,
        totalDamageDealtToChampions: 33639,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 54583,
        totalHeal: 11465,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 198,
        totalTimeCCDealt: 217,
        totalTimeSpentDead: 409,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 5232,
        trueDamageDealtToChampions: 2720,
        trueDamageTaken: 6707,
        turretKills: 2,
        turretTakedowns: 4,
        turretsLost: 6,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 17,
        visionWardsBoughtInGame: 1,
        wardsKilled: 2,
        wardsPlaced: 8,
        win: true
      },
      {
        allInPings: 0,
        assistMePings: 9,
        assists: 16,
        baitPings: 0,
        baronKills: 1,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 281,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 115.00000017881393,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 675,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.01718415891606795,
          controlWardsPlaced: 1,
          damagePerMinute: 633.9252983371306,
          damageTakenOnTeamPercentage: 0.24815149873000925,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 8,
          dodgeSkillShotsSmallWindow: 11,
          doubleAces: 0,
          dragonTakedowns: 2,
          earliestBaron: 2083.768886412002,
          earliestDragonTakedown: 1026.0201391956487,
          earliestElderDragon: 2375.8981544487788,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 1995.34375,
          elderDragonKillsWithOpposingSoul: 1,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 34,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 2,
          epicMonsterKillsWithin30SecondsOfSpawn: 2,
          epicMonsterSteals: 1,
          epicMonsterStolenWithoutSmite: 1,
          flawlessAces: 0,
          fullTeamTakedown: 2,
          gameLength: 2436.3211091098337,
          goldPerMinute: 391.14333416703545,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 15,
          initialBuffCount: 2,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 56.00000008940697,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 2.625,
          killAfterHiddenWithAlly: 6,
          killParticipation: 0.5526315789473685,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 2,
          killsOnLanersEarlyJungleAsJungler: 2,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 1,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 2,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 17.500000029802322,
          maxKillDeficit: 10,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: -45.000000059604645,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6662,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 1,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 18,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 4,
          saveAllyFromDeath: 2,
          scuttleCrabKills: 2,
          skillshotsDodged: 57,
          skillshotsHit: 12,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 14,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 21,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 4,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.16102422118829626,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 4,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 3,
          turretsTakenWithRiftHerald: 10,
          twentyMinionsIn3SecondsCount: 2,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.1679234504699707,
          visionScorePerMinute: 0.6887304134705394,
          wardTakedowns: 2,
          wardTakedownsBefore20M: 1,
          wardsGuarded: 1
        },
        champExperience: 19045,
        champLevel: 18,
        championId: 113,
        championName: 'Sejuani',
        championTransform: 0,
        commandPings: 20,
        consumablesPurchased: 3,
        damageDealtToBuildings: 602,
        damageDealtToObjectives: 28739,
        damageDealtToTurrets: 602,
        damageSelfMitigated: 88256,
        dangerPings: 0,
        deaths: 8,
        detectorWardsPlaced: 1,
        doubleKills: 0,
        dragonKills: 2,
        eligibleForProgression: true,
        enemyMissingPings: 10,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 16,
        goldEarned: 15882,
        goldSpent: 13725,
        holdPings: 4,
        individualPosition: 'JUNGLE',
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 0,
        item0: 3068,
        item1: 3075,
        item2: 3047,
        item3: 6662,
        item4: 3110,
        item5: 1011,
        item6: 3340,
        itemsPurchased: 24,
        killingSprees: 2,
        kills: 5,
        lane: 'JUNGLE',
        largestCriticalStrike: 55,
        largestKillingSpree: 2,
        largestMultiKill: 1,
        longestTimeSpentLiving: 434,
        magicDamageDealt: 77290,
        magicDamageDealtToChampions: 12597,
        magicDamageTaken: 23326,
        needVisionPings: 0,
        neutralMinionsKilled: 146,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 1,
        objectivesStolenAssists: 0,
        onMyWayPings: 33,
        participantId: 2,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5001,
            flex: 5002,
            offense: 5005
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8439,
                  var1: 959,
                  var2: 1743,
                  var3: 0
                },
                {
                  perk: 8463,
                  var1: 2952,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8429,
                  var1: 70,
                  var2: 21,
                  var3: 10
                },
                {
                  perk: 8242,
                  var1: 124,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8400
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 9111,
                  var1: 1849,
                  var2: 420,
                  var3: 0
                },
                {
                  perk: 9104,
                  var1: 15,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8000
            }
          ]
        },
        physicalDamageDealt: 115969,
        physicalDamageDealtToChampions: 10919,
        physicalDamageTaken: 24559,
        profileIcon: 503,
        pushPings: 0,
        puuid:
          '0pkNAVmAHAxdqgODFsrByh_Mgmk4VHVSFP9t8xN4M04gS1BsyZjaCEFyQ93dNSHkuch0z0bIf-9NtQ',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'NONE',
        sightWardsBoughtInGame: 0,
        spell1Casts: 50,
        spell2Casts: 133,
        spell3Casts: 86,
        spell4Casts: 12,
        summoner1Casts: 7,
        summoner1Id: 4,
        summoner2Casts: 23,
        summoner2Id: 11,
        summonerId: 'oFRbdOwNhjicS5QYopXMpXvtSNaaSJ8upX0mxjxV2CQajAQ',
        summonerLevel: 281,
        summonerName: 'N2theoel',
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: 'JUNGLE',
        timeCCingOthers: 46,
        timePlayed: 2436,
        totalDamageDealt: 245709,
        totalDamageDealtToChampions: 25740,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 51723,
        totalHeal: 4296,
        totalHealsOnTeammates: 1995,
        totalMinionsKilled: 67,
        totalTimeCCDealt: 2056,
        totalTimeSpentDead: 263,
        totalUnitsHealed: 5,
        tripleKills: 0,
        trueDamageDealt: 52450,
        trueDamageDealtToChampions: 2223,
        trueDamageTaken: 3837,
        turretKills: 0,
        turretTakedowns: 3,
        turretsLost: 6,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 27,
        visionWardsBoughtInGame: 1,
        wardsKilled: 2,
        wardsPlaced: 15,
        win: true
      },
      {
        allInPings: 0,
        assistMePings: 0,
        assists: 11,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 4,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 750,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 8.000000029802322,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 900,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.24817201324973276,
          controlWardsPlaced: 3,
          damagePerMinute: 1060.0163281405837,
          damageTakenOnTeamPercentage: 0.23882450874113306,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 7,
          dodgeSkillShotsSmallWindow: 6,
          doubleAces: 0,
          dragonTakedowns: 0,
          earliestBaron: 2083.768886412002,
          earliestElderDragon: 2375.8981544487788,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 1,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 11,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 0,
          fullTeamTakedown: 2,
          gameLength: 2436.3211091098337,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 413.42307605564986,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 4,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 3.142857142857143,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.5789473684210527,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 2,
          killsNearEnemyTurret: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 2,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 61,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 35,
          maxKillDeficit: 10,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6657,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 4,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 17,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 1,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 36,
          skillshotsHit: 12,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 4,
          stealthWardsPlaced: 11,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 22,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 1,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.2692561791325458,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 4,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 4,
          turretsTakenWithRiftHerald: 10,
          twentyMinionsIn3SecondsCount: 10,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.19719403982162476,
          visionScorePerMinute: 0.6579980581055459,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0
        },
        champExperience: 22275,
        champLevel: 18,
        championId: 69,
        championName: 'Cassiopeia',
        championTransform: 0,
        commandPings: 2,
        consumablesPurchased: 5,
        damageDealtToBuildings: 2700,
        damageDealtToObjectives: 12418,
        damageDealtToTurrets: 2700,
        damageSelfMitigated: 40233,
        dangerPings: 0,
        deaths: 7,
        detectorWardsPlaced: 3,
        doubleKills: 1,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 13,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 16787,
        goldSpent: 14725,
        holdPings: 0,
        individualPosition: 'MIDDLE',
        inhibitorKills: 0,
        inhibitorTakedowns: 1,
        inhibitorsLost: 0,
        item0: 3040,
        item1: 3157,
        item2: 3116,
        item3: 6657,
        item4: 4637,
        item5: 0,
        item6: 3340,
        itemsPurchased: 24,
        killingSprees: 3,
        kills: 11,
        lane: 'MIDDLE',
        largestCriticalStrike: 0,
        largestKillingSpree: 4,
        largestMultiKill: 2,
        longestTimeSpentLiving: 631,
        magicDamageDealt: 183025,
        magicDamageDealtToChampions: 40433,
        magicDamageTaken: 21679,
        needVisionPings: 0,
        neutralMinionsKilled: 8,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 1,
        participantId: 3,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5003,
            flex: 5008,
            offense: 5008
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8010,
                  var1: 770,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8009,
                  var1: 6112,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 9105,
                  var1: 18,
                  var2: 20,
                  var3: 0
                },
                {
                  perk: 8299,
                  var1: 1910,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8000
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8429,
                  var1: 70,
                  var2: 12,
                  var3: 10
                },
                {
                  perk: 8451,
                  var1: 307,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8400
            }
          ]
        },
        physicalDamageDealt: 18719,
        physicalDamageDealtToChampions: 2113,
        physicalDamageTaken: 26011,
        profileIcon: 4778,
        pushPings: 0,
        puuid:
          '9FjB6i7tI4u23tLjO7Rn_VJ2P23M1FGP4bzndCLpQwYyQHBJ9LpQ2EbZn4zCdRzmmZqpbgsCKf0aNQ',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'SOLO',
        sightWardsBoughtInGame: 0,
        spell1Casts: 242,
        spell2Casts: 43,
        spell3Casts: 452,
        spell4Casts: 13,
        summoner1Casts: 2,
        summoner1Id: 12,
        summoner2Casts: 5,
        summoner2Id: 4,
        summonerId: 'JEYiokaxuRj6aYDTjmMTRD7XMUGsq3NWn_sccl3ooqkruSc',
        summonerLevel: 348,
        summonerName: 'delicious ice',
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: 'MIDDLE',
        timeCCingOthers: 63,
        timePlayed: 2436,
        totalDamageDealt: 203678,
        totalDamageDealtToChampions: 43042,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 49779,
        totalHeal: 15474,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 209,
        totalTimeCCDealt: 706,
        totalTimeSpentDead: 286,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 1933,
        trueDamageDealtToChampions: 495,
        trueDamageTaken: 2088,
        turretKills: 1,
        turretTakedowns: 4,
        turretsLost: 6,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 26,
        visionWardsBoughtInGame: 3,
        wardsKilled: 0,
        wardsPlaced: 14,
        win: true
      },
      {
        allInPings: 1,
        assistMePings: 9,
        assists: 4,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 1,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 378,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 2.5,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 375,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 1107.160860247013,
          damageTakenOnTeamPercentage: 0.1626081036376616,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 11,
          dodgeSkillShotsSmallWindow: 12,
          doubleAces: 0,
          dragonTakedowns: 2,
          earliestBaron: 2083.768886412002,
          earliestDragonTakedown: 2375.8981544487788,
          earliestElderDragon: 2375.8981544487788,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 1,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 0,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 0,
          fullTeamTakedown: 2,
          gameLength: 2436.3211091098337,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 426.14148689921126,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 1,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 1.2727272727272727,
          killAfterHiddenWithAlly: 4,
          killParticipation: 0.3684210526315789,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 2,
          killsNearEnemyTurret: 1,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 2,
          laneMinionsFirst10Minutes: 76,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 57.999999940395355,
          maxKillDeficit: 10,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6672,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 11,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 1,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 64,
          skillshotsHit: 23,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          soloTurretsLategame: 1,
          stealthWardsPlaced: 5,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 14,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 3,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.28123142540468177,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 4,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 5,
          turretsTakenWithRiftHerald: 10,
          twentyMinionsIn3SecondsCount: 13,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.16631782054901123,
          visionScorePerMinute: 0.5682585169747015,
          wardTakedowns: 2,
          wardTakedownsBefore20M: 1,
          wardsGuarded: 0
        },
        champExperience: 19529,
        champLevel: 18,
        championId: 145,
        championName: 'Kaisa',
        championTransform: 0,
        commandPings: 18,
        consumablesPurchased: 1,
        damageDealtToBuildings: 7741,
        damageDealtToObjectives: 25194,
        damageDealtToTurrets: 7741,
        damageSelfMitigated: 21821,
        dangerPings: 0,
        deaths: 11,
        detectorWardsPlaced: 0,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 15,
        enemyVisionPings: 1,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 14,
        goldEarned: 17303,
        goldSpent: 15730,
        holdPings: 1,
        individualPosition: 'BOTTOM',
        inhibitorKills: 1,
        inhibitorTakedowns: 1,
        inhibitorsLost: 0,
        item0: 6672,
        item1: 2421,
        item2: 3006,
        item3: 3046,
        item4: 3036,
        item5: 6675,
        item6: 3363,
        itemsPurchased: 23,
        killingSprees: 2,
        kills: 10,
        lane: 'BOTTOM',
        largestCriticalStrike: 545,
        largestKillingSpree: 3,
        largestMultiKill: 1,
        longestTimeSpentLiving: 413,
        magicDamageDealt: 36615,
        magicDamageDealtToChampions: 13358,
        magicDamageTaken: 10737,
        needVisionPings: 0,
        neutralMinionsKilled: 4,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 1,
        onMyWayPings: 49,
        participantId: 4,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5005
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8008,
                  var1: 89,
                  var2: 11,
                  var3: 0
                },
                {
                  perk: 8009,
                  var1: 2806,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 9103,
                  var1: 28,
                  var2: 10,
                  var3: 0
                },
                {
                  perk: 8014,
                  var1: 913,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8000
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8304,
                  var1: 9,
                  var2: 4,
                  var3: 5
                },
                {
                  perk: 8345,
                  var1: 3,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8300
            }
          ]
        },
        physicalDamageDealt: 216719,
        physicalDamageDealtToChampions: 27799,
        physicalDamageTaken: 21419,
        profileIcon: 16,
        pushPings: 0,
        puuid:
          'xzKMuv1c0l-rert5giH4MzCuShb6Uk6k0nB0Gp8xRZE2LAsYfEXmNd8tKXX4dVE2QofDFCNfckSgNw',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'CARRY',
        sightWardsBoughtInGame: 0,
        spell1Casts: 96,
        spell2Casts: 69,
        spell3Casts: 202,
        spell4Casts: 11,
        summoner1Casts: 5,
        summoner1Id: 4,
        summoner2Casts: 9,
        summoner2Id: 3,
        summonerId:
          '71n3SLbxljtWbV5pcE73Hnq_ucpLzETyL-_Iy9LyRpbpoZt3M8bExOwyuQ',
        summonerLevel: 31,
        summonerName: 'Frathaen',
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: 'BOTTOM',
        timeCCingOthers: 3,
        timePlayed: 2436,
        totalDamageDealt: 292890,
        totalDamageDealtToChampions: 44956,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 33893,
        totalHeal: 1784,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 279,
        totalTimeCCDealt: 66,
        totalTimeSpentDead: 403,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 39555,
        trueDamageDealtToChampions: 3798,
        trueDamageTaken: 1736,
        turretKills: 5,
        turretTakedowns: 5,
        turretsLost: 6,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 23,
        visionWardsBoughtInGame: 0,
        wardsKilled: 2,
        wardsPlaced: 10,
        win: true
      },
      {
        allInPings: 0,
        assistMePings: 4,
        assists: 24,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 1,
        challenges: {
          '12AssistStreakCount': 1,
          abilityUses: 245,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.23751647126548553,
          controlWardsPlaced: 10,
          damagePerMinute: 307.29119274625924,
          damageTakenOnTeamPercentage: 0.08854458828319126,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 4,
          dodgeSkillShotsSmallWindow: 12,
          doubleAces: 0,
          dragonTakedowns: 2,
          earliestBaron: 2083.768886412002,
          earliestDragonTakedown: 1026.0201391956487,
          earliestElderDragon: 2375.8981544487788,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 16637.205078125,
          elderDragonKillsWithOpposingSoul: 1,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 27,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 0,
          fullTeamTakedown: 2,
          gameLength: 2436.3211091098337,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 275.2219084772012,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 9,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 6.5,
          killAfterHiddenWithAlly: 5,
          killParticipation: 0.6842105263157895,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 1,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 4,
          laneMinionsFirst10Minutes: 2,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 0,
          maxKillDeficit: 10,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 4005,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 1,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 23,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 1,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 64,
          skillshotsHit: 68,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 31,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 26,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 3,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.07805545088638212,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 4,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 4,
          turretsTakenWithRiftHerald: 10,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.33925604820251465,
          visionScorePerMinute: 2.083972714476448,
          wardTakedowns: 7,
          wardTakedownsBefore20M: 3,
          wardsGuarded: 0
        },
        champExperience: 17015,
        champLevel: 17,
        championId: 267,
        championName: 'Nami',
        championTransform: 0,
        commandPings: 1,
        consumablesPurchased: 15,
        damageDealtToBuildings: 140,
        damageDealtToObjectives: 585,
        damageDealtToTurrets: 140,
        damageSelfMitigated: 8524,
        dangerPings: 0,
        deaths: 4,
        detectorWardsPlaced: 10,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 3,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 11175,
        goldSpent: 9650,
        holdPings: 0,
        individualPosition: 'UTILITY',
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 0,
        item0: 4005,
        item1: 3853,
        item2: 3158,
        item3: 2055,
        item4: 3011,
        item5: 6616,
        item6: 3364,
        itemsPurchased: 32,
        killingSprees: 0,
        kills: 2,
        lane: 'BOTTOM',
        largestCriticalStrike: 0,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        longestTimeSpentLiving: 595,
        magicDamageDealt: 22254,
        magicDamageDealtToChampions: 11008,
        magicDamageTaken: 8141,
        needVisionPings: 0,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 1,
        participantId: 5,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5008
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8214,
                  var1: 838,
                  var2: 2658,
                  var3: 0
                },
                {
                  perk: 8226,
                  var1: 250,
                  var2: 556,
                  var3: 0
                },
                {
                  perk: 8210,
                  var1: 21,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8237,
                  var1: 510,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8200
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8347,
                  var1: 0,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8304,
                  var1: 9,
                  var2: 4,
                  var3: 5
                }
              ],
              style: 8300
            }
          ]
        },
        physicalDamageDealt: 3508,
        physicalDamageDealtToChampions: 574,
        physicalDamageTaken: 10010,
        profileIcon: 1031,
        pushPings: 0,
        puuid:
          '2DUofDHHiwu-YTN3yW3tOrDDcxXPULW4mN70Qf2j0KyRKtN6ptlr7wxeqQhiewh4OcCMuE3AYYMdMg',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'SUPPORT',
        sightWardsBoughtInGame: 0,
        spell1Casts: 40,
        spell2Casts: 93,
        spell3Casts: 97,
        spell4Casts: 15,
        summoner1Casts: 8,
        summoner1Id: 7,
        summoner2Casts: 4,
        summoner2Id: 4,
        summonerId: '8RohVTnZxbo29pvggvaAjamHUiyrfx4D4KXOnjQwO6_BocU',
        summonerLevel: 210,
        summonerName: 'Amandila',
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: 'UTILITY',
        timeCCingOthers: 39,
        timePlayed: 2436,
        totalDamageDealt: 26956,
        totalDamageDealtToChampions: 12477,
        totalDamageShieldedOnTeammates: 3106,
        totalDamageTaken: 18455,
        totalHeal: 19671,
        totalHealsOnTeammates: 13531,
        totalMinionsKilled: 12,
        totalTimeCCDealt: 307,
        totalTimeSpentDead: 115,
        totalUnitsHealed: 5,
        tripleKills: 0,
        trueDamageDealt: 1194,
        trueDamageDealtToChampions: 894,
        trueDamageTaken: 304,
        turretKills: 0,
        turretTakedowns: 4,
        turretsLost: 6,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 84,
        visionWardsBoughtInGame: 12,
        wardsKilled: 7,
        wardsPlaced: 41,
        win: true
      },
      {
        allInPings: 0,
        assistMePings: 0,
        assists: 14,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 489,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 8.000000029802322,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 1,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.050818466798236595,
          controlWardsPlaced: 1,
          damagePerMinute: 1365.8807010012163,
          damageTakenOnTeamPercentage: 0.3983077451940544,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 6,
          dodgeSkillShotsSmallWindow: 3,
          doubleAces: 0,
          dragonTakedowns: 0,
          earliestBaron: 1704.8540433872563,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 0,
          enemyJungleMonsterKills: 10.000000029802322,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          firstTurretKilledTime: 817.6631648534789,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2436.3211091098337,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 420.92877347547045,
          hadOpenNexus: 0,
          highestChampionDamage: 1,
          highestCrowdControlScore: 1,
          immobilizeAndKillWithAlly: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 3.1666666666666665,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.475,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 1,
          killsNearEnemyTurret: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 10,
          laneMinionsFirst10Minutes: 72,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 67.5,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 3,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 3084,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 16,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 3,
          skillshotsDodged: 20,
          skillshotsHit: 92,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          soloTurretsLategame: 2,
          stealthWardsPlaced: 14,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 4,
          takedownOnFirstTurret: 0,
          takedowns: 19,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 1,
          takedownsFirstXMinutes: 3,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.31212414048624293,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 2,
          turretPlatesTaken: 2,
          turretTakedowns: 4,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 12,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 1.0211246013641357,
          visionScorePerMinute: 0.8657646534344844,
          wardTakedowns: 5,
          wardTakedownsBefore20M: 1,
          wardsGuarded: 2
        },
        champExperience: 22227,
        champLevel: 18,
        championId: 36,
        championName: 'DrMundo',
        championTransform: 0,
        commandPings: 8,
        consumablesPurchased: 3,
        damageDealtToBuildings: 8698,
        damageDealtToObjectives: 11712,
        damageDealtToTurrets: 8698,
        damageSelfMitigated: 110878,
        dangerPings: 0,
        deaths: 6,
        detectorWardsPlaced: 1,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 10,
        enemyVisionPings: 0,
        firstBloodAssist: true,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 6,
        goldEarned: 17091,
        goldSpent: 16125,
        holdPings: 0,
        individualPosition: 'TOP',
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 3075,
        item1: 3193,
        item2: 3047,
        item3: 3068,
        item4: 3065,
        item5: 3084,
        item6: 3340,
        itemsPurchased: 23,
        killingSprees: 1,
        kills: 5,
        lane: 'TOP',
        largestCriticalStrike: 0,
        largestKillingSpree: 4,
        largestMultiKill: 1,
        longestTimeSpentLiving: 598,
        magicDamageDealt: 115204,
        magicDamageDealtToChampions: 35076,
        magicDamageTaken: 30034,
        needVisionPings: 0,
        neutralMinionsKilled: 30,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 7,
        participantId: 6,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5001,
            flex: 5002,
            offense: 5005
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8437,
                  var1: 3538,
                  var2: 2806,
                  var3: 0
                },
                {
                  perk: 8446,
                  var1: 4276,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8444,
                  var1: 3095,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8451,
                  var1: 381,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8400
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8410,
                  var1: 120,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8304,
                  var1: 10,
                  var2: 3,
                  var3: 0
                }
              ],
              style: 8300
            }
          ]
        },
        physicalDamageDealt: 163866,
        physicalDamageDealtToChampions: 17859,
        physicalDamageTaken: 44761,
        profileIcon: 1113,
        pushPings: 0,
        puuid:
          'pTEkf0XXZU6rojXpyBJDcRGLmCm4C3qb715oV7PssrtnWLjIWk3MQvhzTVjgdrrIX5-_4Vv-YlQTSQ',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'SOLO',
        sightWardsBoughtInGame: 0,
        spell1Casts: 273,
        spell2Casts: 63,
        spell3Casts: 139,
        spell4Casts: 14,
        summoner1Casts: 4,
        summoner1Id: 12,
        summoner2Casts: 5,
        summoner2Id: 4,
        summonerId: 'eUgXvpikcr8NOfxhIKX3bCQx0XVCmCunqx1qKWkmjRuOL_U',
        summonerLevel: 137,
        summonerName: 'F3rnu5',
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: 'TOP',
        timeCCingOthers: 28,
        timePlayed: 2436,
        totalDamageDealt: 288649,
        totalDamageDealtToChampions: 55462,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 80536,
        totalHeal: 42850,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 253,
        totalTimeCCDealt: 985,
        totalTimeSpentDead: 181,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 9578,
        trueDamageDealtToChampions: 2526,
        trueDamageTaken: 5741,
        turretKills: 3,
        turretTakedowns: 4,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 35,
        visionWardsBoughtInGame: 1,
        wardsKilled: 5,
        wardsPlaced: 15,
        win: false
      },
      {
        allInPings: 0,
        assistMePings: 4,
        assists: 4,
        baitPings: 0,
        baronKills: 1,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 143,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 114.00000014901161,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 454.9656199280706,
          damageTakenOnTeamPercentage: 0.2004968099201405,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 10,
          dodgeSkillShotsSmallWindow: 2,
          doubleAces: 0,
          dragonTakedowns: 4,
          earliestBaron: 1704.8540433872563,
          earliestDragonTakedown: 659.4505132402372,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 0,
          enemyJungleMonsterKills: 15.000000029802322,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 1,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          firstTurretKilledTime: 817.6631648534789,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2436.3211091098337,
          goldPerMinute: 362.76328611109057,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 0,
          initialBuffCount: 2,
          initialCrabCount: 2,
          jungleCsBefore10Minutes: 56.000000059604645,
          junglerKillsEarlyJungle: 1,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 1,
          kda: 1.1,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.275,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 1,
          killsNearEnemyTurret: 3,
          killsOnLanersEarlyJungleAsJungler: 1,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 0,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 11,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: -49.00000008940697,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6672,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 9,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 5,
          skillshotsDodged: 15,
          skillshotsHit: 2,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 12,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 11,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 1,
          takedownsFirstXMinutes: 3,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.10396643935795186,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 3,
          turretTakedowns: 2,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 1,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.2018125057220459,
          visionScorePerMinute: 0.8277248275312303,
          wardTakedowns: 4,
          wardTakedownsBefore20M: 2,
          wardsGuarded: 0
        },
        champExperience: 16914,
        champLevel: 17,
        championId: 29,
        championName: 'Twitch',
        championTransform: 0,
        commandPings: 5,
        consumablesPurchased: 2,
        damageDealtToBuildings: 3179,
        damageDealtToObjectives: 43461,
        damageDealtToTurrets: 3179,
        damageSelfMitigated: 23351,
        dangerPings: 0,
        deaths: 10,
        detectorWardsPlaced: 0,
        doubleKills: 0,
        dragonKills: 3,
        eligibleForProgression: true,
        enemyMissingPings: 15,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: true,
        firstTowerAssist: true,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 1,
        goldEarned: 14730,
        goldSpent: 14350,
        holdPings: 0,
        individualPosition: 'JUNGLE',
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 3153,
        item1: 3115,
        item2: 6672,
        item3: 3006,
        item4: 3036,
        item5: 0,
        item6: 3340,
        itemsPurchased: 25,
        killingSprees: 2,
        kills: 7,
        lane: 'JUNGLE',
        largestCriticalStrike: 563,
        largestKillingSpree: 3,
        largestMultiKill: 1,
        longestTimeSpentLiving: 934,
        magicDamageDealt: 28079,
        magicDamageDealtToChampions: 2853,
        magicDamageTaken: 15706,
        needVisionPings: 0,
        neutralMinionsKilled: 171,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 30,
        participantId: 7,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5005
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 9923,
                  var1: 51,
                  var2: 89,
                  var3: 0
                },
                {
                  perk: 8139,
                  var1: 779,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8138,
                  var1: 18,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8135,
                  var1: 400,
                  var2: 4,
                  var3: 0
                }
              ],
              style: 8100
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8009,
                  var1: 1238,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 9104,
                  var1: 17,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8000
            }
          ]
        },
        physicalDamageDealt: 162889,
        physicalDamageDealtToChampions: 10304,
        physicalDamageTaken: 23864,
        profileIcon: 539,
        pushPings: 0,
        puuid:
          '-jDFFhYg-D2loE_gqKVrS3gfPW9ciz-u7SeWLVxkjFd_3JjeZP86olVEYjxDR6HhifsbbYirjjZu6w',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'NONE',
        sightWardsBoughtInGame: 0,
        spell1Casts: 40,
        spell2Casts: 37,
        spell3Casts: 61,
        spell4Casts: 5,
        summoner1Casts: 4,
        summoner1Id: 4,
        summoner2Casts: 17,
        summoner2Id: 11,
        summonerId: 'bz0Oe-mUnA9i8kCzyARvoUKKR5gnkhm5NTNC29vLSWR4Aeo',
        summonerLevel: 390,
        summonerName: 'Adolf Snitzler',
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: 'JUNGLE',
        timeCCingOthers: 7,
        timePlayed: 2436,
        totalDamageDealt: 267667,
        totalDamageDealtToChampions: 18474,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 40540,
        totalHeal: 2417,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 38,
        totalTimeCCDealt: 396,
        totalTimeSpentDead: 438,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 76697,
        trueDamageDealtToChampions: 5316,
        trueDamageTaken: 969,
        turretKills: 1,
        turretTakedowns: 2,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 33,
        visionWardsBoughtInGame: 0,
        wardsKilled: 4,
        wardsPlaced: 12,
        win: false
      },
      {
        allInPings: 0,
        assistMePings: 0,
        assists: 13,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 239,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 17.000000029802322,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 450,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardsPlaced: 1,
          damagePerMinute: 902.5493042164787,
          damageTakenOnTeamPercentage: 0.17428737328653976,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 8,
          dodgeSkillShotsSmallWindow: 4,
          doubleAces: 0,
          dragonTakedowns: 3,
          earliestBaron: 1704.8540433872563,
          earliestDragonTakedown: 659.4505132402372,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 29,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 1,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          fastestLegendary: 1123.7468194767466,
          firstTurretKilledTime: 817.6631648534789,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2436.3211091098337,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 438.8815909269356,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 16,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 3.75,
          killAfterHiddenWithAlly: 1,
          killParticipation: 0.75,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 3,
          killsNearEnemyTurret: 4,
          killsOnOtherLanesEarlyJungleAsLaner: 3,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 1,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 3,
          laneMinionsFirst10Minutes: 53,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 1,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 5,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6692,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 3,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 21,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 24,
          skillshotsHit: 5,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 6,
          stealthWardsPlaced: 12,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 2,
          takedownOnFirstTurret: 0,
          takedowns: 30,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 1,
          takedownsFirstXMinutes: 10,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.20624599616828043,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 3,
          turretTakedowns: 2,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 7,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.24563097953796387,
          visionScorePerMinute: 0.8196227644570676,
          wardTakedowns: 2,
          wardTakedownsBefore20M: 1,
          wardsGuarded: 1
        },
        champExperience: 19644,
        champLevel: 18,
        championId: 80,
        championName: 'Pantheon',
        championTransform: 0,
        commandPings: 19,
        consumablesPurchased: 2,
        damageDealtToBuildings: 2276,
        damageDealtToObjectives: 15705,
        damageDealtToTurrets: 2276,
        damageSelfMitigated: 38154,
        dangerPings: 0,
        deaths: 8,
        detectorWardsPlaced: 1,
        doubleKills: 1,
        dragonKills: 1,
        eligibleForProgression: true,
        enemyMissingPings: 5,
        enemyVisionPings: 0,
        firstBloodAssist: true,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 1,
        goldEarned: 17820,
        goldSpent: 17575,
        holdPings: 0,
        individualPosition: 'MIDDLE',
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 3071,
        item1: 6035,
        item2: 3111,
        item3: 3153,
        item4: 3161,
        item5: 6692,
        item6: 3340,
        itemsPurchased: 26,
        killingSprees: 4,
        kills: 17,
        lane: 'MIDDLE',
        largestCriticalStrike: 0,
        largestKillingSpree: 8,
        largestMultiKill: 2,
        longestTimeSpentLiving: 576,
        magicDamageDealt: 6231,
        magicDamageDealtToChampions: 1648,
        magicDamageTaken: 15143,
        needVisionPings: 0,
        neutralMinionsKilled: 23,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 10,
        participantId: 8,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5003,
            flex: 5008,
            offense: 5008
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8005,
                  var1: 2547,
                  var2: 1433,
                  var3: 1114
                },
                {
                  perk: 9111,
                  var1: 1341,
                  var2: 600,
                  var3: 0
                },
                {
                  perk: 9105,
                  var1: 9,
                  var2: 50,
                  var3: 0
                },
                {
                  perk: 8014,
                  var1: 1135,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8000
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8143,
                  var1: 1596,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8135,
                  var1: 550,
                  var2: 5,
                  var3: 0
                }
              ],
              style: 8100
            }
          ]
        },
        physicalDamageDealt: 175657,
        physicalDamageDealtToChampions: 33321,
        physicalDamageTaken: 18832,
        profileIcon: 5641,
        pushPings: 0,
        puuid:
          'aJpxtgajzgXG60HOETZVEdeGG75snVb5DtylxYi7R3Yj1uMFnQxYfgxJlyF6mTmnVR9bj1RWunHWJg',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'SOLO',
        sightWardsBoughtInGame: 0,
        spell1Casts: 160,
        spell2Casts: 37,
        spell3Casts: 33,
        spell4Casts: 9,
        summoner1Casts: 9,
        summoner1Id: 14,
        summoner2Casts: 6,
        summoner2Id: 4,
        summonerId: 'FYAINzZRMIPemyV5gyMW_24RLDllxQU49mWcH5XxxtMCdV4',
        summonerLevel: 91,
        summonerName: 'Tas Geriausias',
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: 'MIDDLE',
        timeCCingOthers: 31,
        timePlayed: 2436,
        totalDamageDealt: 198226,
        totalDamageDealtToChampions: 36648,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 35240,
        totalHeal: 6372,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 162,
        totalTimeCCDealt: 69,
        totalTimeSpentDead: 378,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 16337,
        trueDamageDealtToChampions: 1677,
        trueDamageTaken: 1263,
        turretKills: 1,
        turretTakedowns: 2,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 33,
        visionWardsBoughtInGame: 1,
        wardsKilled: 2,
        wardsPlaced: 13,
        win: false
      },
      {
        allInPings: 1,
        assistMePings: 4,
        assists: 11,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 1,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 514,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 18.000000059604645,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.19732561708202082,
          controlWardsPlaced: 1,
          damagePerMinute: 937.4716751046441,
          damageTakenOnTeamPercentage: 0.1223327729679394,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 5,
          dodgeSkillShotsSmallWindow: 0,
          doubleAces: 0,
          dragonTakedowns: 1,
          earliestBaron: 1704.8540433872563,
          earliestDragonTakedown: 1674.1332025871475,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 0,
          enemyJungleMonsterKills: 4,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          firstTurretKilledTime: 817.6631648534789,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2436.3211091098337,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 379.37540706106154,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 1,
          kda: 3.8,
          killAfterHiddenWithAlly: 1,
          killParticipation: 0.475,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 1,
          killsNearEnemyTurret: 1,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 1,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 11,
          laneMinionsFirst10Minutes: 78,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 13,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6672,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 1,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 15,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 4,
          skillshotsHit: 152,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          stealthWardsPlaced: 2,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 1,
          takedowns: 19,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 3,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.2142262795043144,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 3,
          turretTakedowns: 2,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 10,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.14260077476501465,
          visionScorePerMinute: 0.4872244050284279,
          wardTakedowns: 4,
          wardTakedownsBefore20M: 1,
          wardsGuarded: 1
        },
        champExperience: 17669,
        champLevel: 17,
        championId: 81,
        championName: 'Ezreal',
        championTransform: 0,
        commandPings: 0,
        consumablesPurchased: 4,
        damageDealtToBuildings: 2107,
        damageDealtToObjectives: 9485,
        damageDealtToTurrets: 2107,
        damageSelfMitigated: 14082,
        dangerPings: 0,
        deaths: 5,
        detectorWardsPlaced: 1,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 0,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: true,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 15404,
        goldSpent: 14975,
        holdPings: 0,
        individualPosition: 'BOTTOM',
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 3077,
        item1: 3508,
        item2: 6694,
        item3: 3042,
        item4: 3158,
        item5: 6672,
        item6: 3363,
        itemsPurchased: 27,
        killingSprees: 2,
        kills: 8,
        lane: 'BOTTOM',
        largestCriticalStrike: 640,
        largestKillingSpree: 4,
        largestMultiKill: 1,
        longestTimeSpentLiving: 445,
        magicDamageDealt: 26110,
        magicDamageDealtToChampions: 13706,
        magicDamageTaken: 12235,
        needVisionPings: 0,
        neutralMinionsKilled: 22,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 9,
        participantId: 9,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5005
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8005,
                  var1: 1109,
                  var2: 591,
                  var3: 518
                },
                {
                  perk: 8009,
                  var1: 3230,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 9103,
                  var1: 22,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8014,
                  var1: 882,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8000
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8304,
                  var1: 9,
                  var2: 4,
                  var3: 5
                },
                {
                  perk: 8345,
                  var1: 3,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8300
            }
          ]
        },
        physicalDamageDealt: 177202,
        physicalDamageDealtToChampions: 21390,
        physicalDamageTaken: 10877,
        profileIcon: 4982,
        pushPings: 0,
        puuid:
          'rNInN8kgRJfPY5U0yFsvlAdnL1TbYH0F_dJgyhyFkJ9AEv6xojuyjTCFHG8VO79K7qW2nqHaYYSfXg',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'CARRY',
        sightWardsBoughtInGame: 0,
        spell1Casts: 386,
        spell2Casts: 69,
        spell3Casts: 42,
        spell4Casts: 17,
        summoner1Casts: 5,
        summoner1Id: 4,
        summoner2Casts: 6,
        summoner2Id: 3,
        summonerId: 'rv10tovzQl-TYTtD50WYdco1fN5rtXXwBUphV6u17yu5f56U',
        summonerLevel: 115,
        summonerName: 'Dejvosakxx',
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: 'BOTTOM',
        timeCCingOthers: 10,
        timePlayed: 2436,
        totalDamageDealt: 220865,
        totalDamageDealtToChampions: 38066,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 24735,
        totalHeal: 7150,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 214,
        totalTimeCCDealt: 151,
        totalTimeSpentDead: 159,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 17553,
        trueDamageDealtToChampions: 2969,
        trueDamageTaken: 1622,
        turretKills: 1,
        turretTakedowns: 2,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 19,
        visionWardsBoughtInGame: 3,
        wardsKilled: 4,
        wardsPlaced: 4,
        win: false
      },
      {
        allInPings: 2,
        assistMePings: 13,
        assists: 14,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          '12AssistStreakCount': 0,
          abilityUses: 268,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 2,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          completeSupportQuestInTime: 1,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.41237268053180914,
          controlWardsPlaced: 7,
          damagePerMinute: 715.2142770136157,
          damageTakenOnTeamPercentage: 0.10457529863132597,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 9,
          dodgeSkillShotsSmallWindow: 0,
          doubleAces: 0,
          dragonTakedowns: 4,
          earliestBaron: 1704.8540433872563,
          earliestDragonTakedown: 659.4505132402372,
          earlyLaningPhaseGoldExpAdvantage: 1,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 11,
          enemyJungleMonsterKills: 1,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          fasterSupportQuestCompletion: 1,
          firstTurretKilledTime: 817.6631648534789,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2436.3211091098337,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 278.7290854839801,
          hadOpenNexus: 0,
          highestWardKills: 1,
          immobilizeAndKillWithAlly: 1,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 1,
          kTurretsDestroyedBeforePlatesFall: 1,
          kda: 1.8888888888888888,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.425,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 1,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 2,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 20,
          laneMinionsFirst10Minutes: 15,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 65,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6653,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 13,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 6,
          skillshotsHit: 109,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 39,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 17,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 1,
          takedownsFirstXMinutes: 6,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.1634371444832104,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 2,
          turretTakedowns: 1,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 3,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.5134454965591431,
          visionScorePerMinute: 3.153979215385235,
          wardTakedowns: 17,
          wardTakedownsBefore20M: 6,
          wardsGuarded: 1
        },
        champExperience: 14522,
        champLevel: 15,
        championId: 74,
        championName: 'Heimerdinger',
        championTransform: 0,
        commandPings: 18,
        consumablesPurchased: 9,
        damageDealtToBuildings: 1161,
        damageDealtToObjectives: 28467,
        damageDealtToTurrets: 1161,
        damageSelfMitigated: 10826,
        dangerPings: 0,
        deaths: 9,
        detectorWardsPlaced: 7,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 5,
        enemyVisionPings: 8,
        firstBloodAssist: true,
        firstBloodKill: false,
        firstTowerAssist: true,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 2,
        goldEarned: 11317,
        goldSpent: 11075,
        holdPings: 0,
        individualPosition: 'UTILITY',
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 6653,
        item1: 3011,
        item2: 2420,
        item3: 3853,
        item4: 3020,
        item5: 4637,
        item6: 3364,
        itemsPurchased: 26,
        killingSprees: 0,
        kills: 3,
        lane: 'BOTTOM',
        largestCriticalStrike: 0,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        longestTimeSpentLiving: 595,
        magicDamageDealt: 97917,
        magicDamageDealtToChampions: 26323,
        magicDamageTaken: 11238,
        needVisionPings: 0,
        neutralMinionsKilled: 3,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 19,
        participantId: 10,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5008
          },
          styles: [
            {
              description: 'primaryStyle',
              selections: [
                {
                  perk: 8229,
                  var1: 2273,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8226,
                  var1: 250,
                  var2: 433,
                  var3: 0
                },
                {
                  perk: 8233,
                  var1: 25,
                  var2: 50,
                  var3: 0
                },
                {
                  perk: 8237,
                  var1: 879,
                  var2: 0,
                  var3: 0
                }
              ],
              style: 8200
            },
            {
              description: 'subStyle',
              selections: [
                {
                  perk: 8345,
                  var1: 3,
                  var2: 0,
                  var3: 0
                },
                {
                  perk: 8304,
                  var1: 9,
                  var2: 4,
                  var3: 5
                }
              ],
              style: 8300
            }
          ]
        },
        physicalDamageDealt: 4081,
        physicalDamageDealtToChampions: 907,
        physicalDamageTaken: 9371,
        profileIcon: 5563,
        pushPings: 0,
        puuid:
          'QpxUlNthyJOgM2m0EjBq3rP4qDRLS7YPGcvD6BMryKkPpu-PBxLWoGxH5LPhE-3XxyPnNFQVGjXi8g',
        quadraKills: 0,
        riotIdName: '',
        riotIdTagline: '',
        role: 'SUPPORT',
        sightWardsBoughtInGame: 0,
        spell1Casts: 107,
        spell2Casts: 89,
        spell3Casts: 53,
        spell4Casts: 19,
        summoner1Casts: 3,
        summoner1Id: 4,
        summoner2Casts: 8,
        summoner2Id: 14,
        summonerId:
          '0QipnZryWbJnJSkCXAcZAUBd7eLzbabTKrVFr2HNlgYSJP_Bv2yQy9cAiw',
        summonerLevel: 82,
        summonerName: 'Nhöno',
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: 'UTILITY',
        timeCCingOthers: 26,
        timePlayed: 2436,
        totalDamageDealt: 103809,
        totalDamageDealtToChampions: 29041,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 21144,
        totalHeal: 1855,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 74,
        totalTimeCCDealt: 168,
        totalTimeSpentDead: 344,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 1810,
        trueDamageDealtToChampions: 1810,
        trueDamageTaken: 535,
        turretKills: 0,
        turretTakedowns: 1,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 128,
        visionWardsBoughtInGame: 7,
        wardsKilled: 17,
        wardsPlaced: 46,
        win: false
      }
    ],
    platformId: 'EUW1',
    queueId: 420,
    teams: [
      {
        bans: [
          {
            championId: 777,
            pickTurn: 1
          },
          {
            championId: 360,
            pickTurn: 2
          },
          {
            championId: 200,
            pickTurn: 3
          },
          {
            championId: 420,
            pickTurn: 4
          },
          {
            championId: 236,
            pickTurn: 5
          }
        ],
        objectives: {
          baron: {
            first: false,
            kills: 1
          },
          champion: {
            first: false,
            kills: 38
          },
          dragon: {
            first: false,
            kills: 2
          },
          inhibitor: {
            first: true,
            kills: 1
          },
          riftHerald: {
            first: true,
            kills: 2
          },
          tower: {
            first: false,
            kills: 9
          }
        },
        teamId: 100,
        win: true
      },
      {
        bans: [
          {
            championId: 119,
            pickTurn: 6
          },
          {
            championId: 90,
            pickTurn: 7
          },
          {
            championId: 235,
            pickTurn: 8
          },
          {
            championId: 427,
            pickTurn: 9
          },
          {
            championId: 114,
            pickTurn: 10
          }
        ],
        objectives: {
          baron: {
            first: true,
            kills: 1
          },
          champion: {
            first: true,
            kills: 40
          },
          dragon: {
            first: true,
            kills: 4
          },
          inhibitor: {
            first: false,
            kills: 0
          },
          riftHerald: {
            first: false,
            kills: 0
          },
          tower: {
            first: true,
            kills: 6
          }
        },
        teamId: 200,
        win: false
      }
    ],
    tournamentCode: ''
  }
}
